# Site settings
title: Initial commit...
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  Sed sed imperdiet neque. Mauris consequat est nec erat aliquet,
  nec vehicula metus malesuada. Class aptent taciti sociosqu ad
  litora torquent per conubia nostra, per inceptos himenaeos.
  Sed tempus erat et mi placerat, id ultricies odio vehicula. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  SurferL

# Build settings
markdown: kramdown
